name: Deploy to Local Directory

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy repo to destination
        run: |
          ls
          cp -R ./* ${{ vars.DEPLOY_DIRECTORY }}
