name: Deploy to Local Directory

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    inputs:
      deploy_directory:
        description: 'Directory to copy the contents of the repo to'
        required: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy repo to destination
        run: |
          cp -R ./rvc-tts-webui/* ${{ vars.DEPLOY_DIRECTORY }}
